export const EnvConfig = () => ({
  nodeEnv: process.env.NODE_ENV || 'development',
  port: process.env.PORT || 3000,
  dbHost: process.env.DB_HOST || 'localhost',
  dbName: process.env.DB_NAME || 'postgres',
  dbPort: process.env.DB_PORT || '5432',
  dbUser: process.env.DB_USER || 'postgres',
  dbPassword: process.env.DB_PASSWORD || 'postgres',
  redisHost: process.env.REDIS_HOST || 'localhost',
  redisPort: process.env.REDIS_PORT || '6379',
  jwtSecret: process.env.JWT_SECRET || 'your_secret',
  jwtExp: process.env.JWT_TTL || '90000',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || 'your_refresh_secret',
  jwtRefreshExp: process.env.JWT_REFRESH_TTL || '125000',
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleCallbackURL: process.env.GOOGLE_CALLBACK_URL || '',
});
